security:
  aes:
    key: ${AES_KEY}
  jwt:
    secret: ${JWT_SECRET}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # ← 이걸 추가
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
# application.yml
ai:
  gemini:
    api:
      key: ${GOOGLE_API_KEY}                          # 환경변수로 주입
      base-url: https://generativelanguage.googleapis.com/v1beta
      model: gemini-2.5-flash-lite
      timeout-seconds: 30
      max-output-tokens: 2048
      temperature: 0.7